### ISSUE TITLE
7.5.5 not working as expected

### ISSUE THREAD

**Issue by smalluk** [CiscoSecurity/amp-05-windows-tune#6]
With the new version 7.5.5 this is no longer working. Tested with both logs generated with admin and without admin (new feature for 7.5.5). It extracts the zip but does not produce the txt file with the output

**Comment by mafranks** [comment]
With the release of 7.5.5 the policy.xml file is extremely limited, which prevents the script from processing the exclusions and other information normally contained within the policy.xml.  Based on that change, this tool would need a complete rewrite to pull that information in another manner.  Unfortunately I don't have time to do that currently.

**Comment by mafranks** [comment]
Added a version 4 that removes references to the policy.xml.  Unfortunately this removes listing exclusions, but that is what had to be done to keep the rest of it working.

**Comment by smalluk** [comment]
Thank you Matthew.
