### ISSUE TITLE
Diag_Analyzer_v1_03.exe has stopped producing the Summary text file since connector 7.5.1.20833 deployed

### ISSUE THREAD

**Issue by King-Alison** [CiscoSecurity/amp-05-windows-tune#7]
Diag_Analyzer_v1_03.exe has stopped producing the Summary text file since I upgraded to the 7.5.1.20833 connector.

C:\AMP-Github-testing>Diag_Analyzer_v1_03.exe

Creating directory

Successfully created the directory C:\AMP-Github-testing\CiscoAMP_Support_Tool_2022_06_15_16_00_51.

Moving log files into the output directory.

Parsing the logs.

Would you like to view the exclusions from your policy? [y/n]y
Traceback (most recent call last):
  File "Diag_Analyzer.py", line 360, in <module>
  File "Diag_Analyzer.py", line 298, in main
  File "Diag_Analyzer.py", line 111, in parse_policy_xml
IndexError: child index out of range
[2108] Failed to execute script Diag_Analyzer

C:\AMP-Github-testing>

**Comment by mafranks** [comment]
Can you please check the policy.xml file inside the zip and see if there are any issues with it?  On 7.5.1 it should be a few hundred lines long.  I just ran one with 7.5.1.20833 and the functionality was normal.

**Comment by mafranks** [comment]
Added a version 4 that removes references to the policy.xml.  Unfortunately this removes listing exclusions, but that is what had to be done to keep the rest of it working.
